### ISSUE TITLE
Parse error - compatibility with nette 2.3

### ISSUE THREAD

**Issue by norbe** [Kdyby/Aop#24]
With nette 2.3 AOP ends with parse error at generated cache.

Problem is with that resolving class name of container ends with NULL, so whole cache is surrounded by "namespace Kdyby\Aop_CG\ { }" instead of "namespace Kdyby\Aop_CG\ContainerClassName { }".

Solution is to replace line https://github.com/Kdyby/Aop/blob/master/src/Kdyby/Aop/DI/AopExtension.php#L77 with 
$cg = $file->getNamespace('Kdyby\Aop_CG\\\\' . $builder->getClassName());

I have no idea how to prepare patch as there is no 2.3 branch. Do you plann it? Or should I check for existence of method getClassName?

**Comment by fprochazka** [comment]
Fixed by https://github.com/Kdyby/Aop/commit/5b035035f08d7e40c093e7c225e2a52fc79ddb3c

**Comment by fprochazka** [comment]
Thank you for reporting!
