### ISSUE TITLE
Kdyby/aop on presenters => autowire false skip

### ISSUE THREAD

**Issue by norbe** [Kdyby/Aop#27]
Is there any reason, why kdyby/aop is not used at non autowired services?

Currently I'm not able to use kdyby/aop on presenters becouse of combination of:
https://github.com/Kdyby/Aop/blob/master/src/Kdyby/Aop/DI/AopExtension.php#L220
and
https://github.com/nette/application/blob/master/src/Bridges/ApplicationDI/ApplicationExtension.php#L111

**Comment by fprochazka** [comment]
Not really. The AopExtension lookup of classes should be refactored, parts can be removed completely, nette/di has some pretty new features.
