### ISSUE TITLE
When i use AOP in presenter it takes wrong path to template 

### ISSUE THREAD

**Issue by AliAmjid** [Kdyby/Aop#42]
Page not found. Missing template 'temp/cache/templates/Homepage/default.latte'.

**Comment by AliAmjid** [comment]
Offcourse that be fixed by this in BasePresneter
```php
	public function startup() {
		parent::startup();
		$this->template->setFile(__DIR__ . "/../../templates/{$this->name}/{$this->action}.latte");
	}

 But maybe this should be fixed in library. 
By replacing of __DIR__ with path of "real file" or something like this while building "cache duplicate of file". 


```

**Comment by dakorpar** [comment]
Hi, I don't see that as an issue of this library and it's not fixable in it, nor it should be fixed here.
I usually just have my own BasePresenter where I put mine behavior for formatTemplateFiles
 so I don't have this problems. I also recommend avoiding AOP in presenters and use them in logic classes and keep presenters as simple as possible.

**Comment by AliAmjid** [comment]
Should be fixed in BasePresenter.
